services:
  db:
    image: postgres:16
    container_name: asset-management-db
    command: ["postgres", "-c", "log_min_messages=warning"]
    environment:
      POSTGRES_DB: asset_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5400:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d asset_management"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
      build:
        context: .
        dockerfile: AssetManagement.Api/Dockerfile
      container_name: asset-management-api
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Host=db;Database=asset_management;Username=postgres;Password=postgres
      ports:
        - "7001:8080"
      depends_on:
        db:
          condition: service_healthy
volumes:
  pgdata: